backend:
    name: github
    repo: LakewoodPlayhouse/lakewood-playhouse

media_folder: "images/uploads"

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Website settings"
        name: "Contact"
        file: "_data/contact.yml"
        fields:
          - label: "Tagline"
            name: "tagline"
            widget: "string"
          - label: "Telephone"
            name: "tel"
            widget: "string"
          - label: "hours"
            name: "hours"
            widget: "string"
          - label: "hours note"
            name: "hours_note"
            widget: "string"
